### PR TITLE
Initial "TinyGo Preview" implementation

### PR DESCRIPTION
**Pull request by aykevl**
I have been working on a "preview" feature for the TinyGo extension. It does something similar to play.tinygo.org, but with much more flexibility, a nicer UI, and integrated directly in VS Code.
Eventually this should also end up on play.tinygo.org, but for now I'm focusing on the extension.

You can test it this way:

1. Clone this repository, check out the `preview` branch.
2. Open the folder in VS Code.
3. Uninstall the TinyGo extension if you have it installed (it might interfere).
4. Run `vsce package` (see [here](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#packaging-extensions)).
5. Press F5.
6. Select one of the supported targets (`arduino` or `arduino-nano33`).
7. Open a project for TinyGo, and click the "preview" button to the right in the tabbar.

### CODE REVIEW

**Comment by Nerzal** [comment]
Note: 
To be able to execute step 4 it is needed to have vsce installed (to install that you need npm) 

So step 4 is the following if u have not installed vsce
> npm install -g vsce
> npm install
> vsce package

**Comment by Nerzal** [comment]
When having a workspace with multiple projects, the extension is unable to locate the correct project and choses a "random" one. 
I guess it would be nice, if either 

- it is configureable which main.go to use
- it tries to preview the currently open main.go file

I have used https://github.com/Nerzal/tinygo-playground for the test. 

The result preview always looked like the following screenshot
grafik

I also get this exact preview, when i open other projects, which only contain a single main file

**Comment by aykevl** [comment]
> When having a workspace with multiple projects, the extension is unable to locate the correct project and choses a "random" one.
> I guess it would be nice, if either
> 
>    * it is configureable which main.go to use
> 
>    * it tries to preview the currently open main.go file

Yes, this should indeed be improved. I think it's best to initially run `tinygo build` in the directory of the currently open file and maybe make it configurable later (not yet sure how exactly).

**Comment by aykevl** [comment]
> I think it's best to initially run `tinygo build` in the directory of the currently open file

I have implemented this. It uses the directory of the open Go file as the package directory to build. This makes it possible to work in a workspace with multiple projects.

**Comment by aykevl** [comment]
Improved the preview feature a lot, most importantly by adding BBC micro:bit support. I can now open the TinyGo project in VS Code, select the microbit in the TinyGo extension, navigate to src/examples/microbit-blink, and click "preview" to see a blinking LED on the BBC micro:bit (although it's not very visible, I hope to improve that in the future).

**Comment by fiurthorn** [comment]
why is it not merged?

**Comment by aykevl** [comment]
I've essentially rewritten all of it with a better design. I'll push it soon!

**Comment by aykevl** [comment]
I've finally pushed the branch, which is at #5.

**Pull request closed without merging**
